# Generated by Django 3.0.7 on 2020-09-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hamburgerapp', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburgermodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hamburger_image/'),
        ),
    ]
